# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mateusz Koślacz Blog [under construction]
email: contact@mateuszkoslacz.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Mateusz Koślacz and I'm a senior Android developer and a Tech Lead
  of a "Las Motosierras" mobile development team in Movibe / Wirtualna Polska.
  I'm also a co-founder of a Faver startup. I'm an enthusiast of
  a self-explaining, clean, comprehensible and maintainable architecture and
  code that provides long-term maintainable, bulletproof products that can share
  modules. This is my personal blog where I publish my thoughts, observations
  and various curiosities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mkoslacz

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
